# Generated by Django 4.0.4 on 2022-07-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_compra_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra_item',
            old_name='compras',
            new_name='compra',
        ),
    ]
